import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-data-center-colocation-invoice-sla-recovery",
  "engine": "recovery",
  "title": "Data Center Colocation Invoice & SLA Recovery",
  "shortTitle": "Colocation Recovery OS",
  "tagline": "Reconcile power and services, enforce SLAs, and recover every supported credit",
  "industry": "Data Center Commercial Operations",
  "uiPort": 4554,
  "apiPort": 5554,
  "accent": "#4f46e5",
  "currency": "USD",
  "primaryOutcome": "Colocation billing leakage and SLA failures converted into cash credits",
  "valueNarrative": "Connect MSAs, order forms, power readings, PUE clauses, tickets, uptime telemetry, and invoices to contract-supported outcomes.",
  "calculation": {
    "actualKey": "invoicedAmount",
    "expectedKey": "contractAmount",
    "actualLabel": "Provider invoiced amount",
    "expectedLabel": "Contract-supported amount",
    "varianceLabel": "Potential invoice / SLA recovery",
    "direction": "actual-minus-expected",
    "finding": "Contract, meter, service, and SLA evidence identify potentially unsupported colocation charges or credits.",
    "actions": [
      "Reconcile the invoice to orders, meters, and contract rates",
      "Validate uptime, incident, response, and maintenance evidence",
      "Calculate SLA and billing credits",
      "Submit and track the provider claim to settlement"
    ]
  }
},[
feature("msa-and-order-form-library","CRO01","MSA and order-form library","Reconcile msa and order-form library using MSAs, order forms, rack and cross-connect inventories, utility readings, PUE formulas, tickets, telemetry, and invoices.","Produce a governed msa and order-form library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["provider","Colocation Provider","text","Atlas Data Centers"],["site","Facility / Cage","text","IAD-04 Cage C18"],["invoicedAmount","Invoiced Amount","currency",428000],["contractAmount","Contract-Supported Amount","currency",379500]],{amountField:"invoicedAmount",subjects:["Wholesale colocation site","Retail cage deployment","High-density AI cluster","Disaster recovery site","Interconnection portfolio"]}),
feature("site-cage-and-rack-registry","CRO02","Site cage and rack registry","Reconcile site cage and rack registry using MSAs, order forms, rack and cross-connect inventories, utility readings, PUE formulas, tickets, telemetry, and invoices.","Produce a governed site cage and rack registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["provider","Colocation Provider","text","Atlas Data Centers"],["site","Facility / Cage","text","IAD-04 Cage C18"],["invoicedAmount","Invoiced Amount","currency",428000],["contractAmount","Contract-Supported Amount","currency",379500]],{amountField:"invoicedAmount",subjects:["Wholesale colocation site","Retail cage deployment","High-density AI cluster","Disaster recovery site","Interconnection portfolio"]}),
feature("power-meter-ingestion","CRO03","Power meter ingestion","Reconcile power meter ingestion using MSAs, order forms, rack and cross-connect inventories, utility readings, PUE formulas, tickets, telemetry, and invoices.","Produce a governed power meter ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["provider","Colocation Provider","text","Atlas Data Centers"],["site","Facility / Cage","text","IAD-04 Cage C18"],["invoicedAmount","Invoiced Amount","currency",428000],["contractAmount","Contract-Supported Amount","currency",379500]],{amountField:"invoicedAmount",subjects:["Wholesale colocation site","Retail cage deployment","High-density AI cluster","Disaster recovery site","Interconnection portfolio"]}),
feature("pue-and-power-charge-recalculation","CRO04","PUE and power-charge recalculation","Reconcile pue and power-charge recalculation using MSAs, order forms, rack and cross-connect inventories, utility readings, PUE formulas, tickets, telemetry, and invoices.","Produce a governed pue and power-charge recalculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["provider","Colocation Provider","text","Atlas Data Centers"],["site","Facility / Cage","text","IAD-04 Cage C18"],["invoicedAmount","Invoiced Amount","currency",428000],["contractAmount","Contract-Supported Amount","currency",379500]],{amountField:"invoicedAmount",subjects:["Wholesale colocation site","Retail cage deployment","High-density AI cluster","Disaster recovery site","Interconnection portfolio"]}),
feature("cross-connect-inventory-reconciliation","CRO05","Cross-connect inventory reconciliation","Reconcile cross-connect inventory reconciliation using MSAs, order forms, rack and cross-connect inventories, utility readings, PUE formulas, tickets, telemetry, and invoices.","Produce a governed cross-connect inventory reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["provider","Colocation Provider","text","Atlas Data Centers"],["site","Facility / Cage","text","IAD-04 Cage C18"],["invoicedAmount","Invoiced Amount","currency",428000],["contractAmount","Contract-Supported Amount","currency",379500]],{amountField:"invoicedAmount",subjects:["Wholesale colocation site","Retail cage deployment","High-density AI cluster","Disaster recovery site","Interconnection portfolio"]}),
feature("remote-hands-charge-audit","CRO06","Remote-hands charge audit","Reconcile remote-hands charge audit using MSAs, order forms, rack and cross-connect inventories, utility readings, PUE formulas, tickets, telemetry, and invoices.","Produce a governed remote-hands charge audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["provider","Colocation Provider","text","Atlas Data Centers"],["site","Facility / Cage","text","IAD-04 Cage C18"],["invoicedAmount","Invoiced Amount","currency",428000],["contractAmount","Contract-Supported Amount","currency",379500]],{amountField:"invoicedAmount",subjects:["Wholesale colocation site","Retail cage deployment","High-density AI cluster","Disaster recovery site","Interconnection portfolio"]}),
feature("recurring-service-reconciliation","CRO07","Recurring service reconciliation","Reconcile recurring service reconciliation using MSAs, order forms, rack and cross-connect inventories, utility readings, PUE formulas, tickets, telemetry, and invoices.","Produce a governed recurring service reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["provider","Colocation Provider","text","Atlas Data Centers"],["site","Facility / Cage","text","IAD-04 Cage C18"],["invoicedAmount","Invoiced Amount","currency",428000],["contractAmount","Contract-Supported Amount","currency",379500]],{amountField:"invoicedAmount",subjects:["Wholesale colocation site","Retail cage deployment","High-density AI cluster","Disaster recovery site","Interconnection portfolio"]}),
feature("install-and-decommission-billing-control","CRO08","Install and decommission billing control","Reconcile install and decommission billing control using MSAs, order forms, rack and cross-connect inventories, utility readings, PUE formulas, tickets, telemetry, and invoices.","Produce a governed install and decommission billing control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["provider","Colocation Provider","text","Atlas Data Centers"],["site","Facility / Cage","text","IAD-04 Cage C18"],["invoicedAmount","Invoiced Amount","currency",428000],["contractAmount","Contract-Supported Amount","currency",379500]],{amountField:"invoicedAmount",subjects:["Wholesale colocation site","Retail cage deployment","High-density AI cluster","Disaster recovery site","Interconnection portfolio"]}),
feature("uptime-sla-monitoring","CRO09","Uptime SLA monitoring","Reconcile uptime sla monitoring using MSAs, order forms, rack and cross-connect inventories, utility readings, PUE formulas, tickets, telemetry, and invoices.","Produce a governed uptime sla monitoring decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["provider","Colocation Provider","text","Atlas Data Centers"],["site","Facility / Cage","text","IAD-04 Cage C18"],["invoicedAmount","Invoiced Amount","currency",428000],["contractAmount","Contract-Supported Amount","currency",379500]],{amountField:"invoicedAmount",subjects:["Wholesale colocation site","Retail cage deployment","High-density AI cluster","Disaster recovery site","Interconnection portfolio"]}),
feature("incident-and-maintenance-evidence","CRO10","Incident and maintenance evidence","Reconcile incident and maintenance evidence using MSAs, order forms, rack and cross-connect inventories, utility readings, PUE formulas, tickets, telemetry, and invoices.","Produce a governed incident and maintenance evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["provider","Colocation Provider","text","Atlas Data Centers"],["site","Facility / Cage","text","IAD-04 Cage C18"],["invoicedAmount","Invoiced Amount","currency",428000],["contractAmount","Contract-Supported Amount","currency",379500]],{amountField:"invoicedAmount",subjects:["Wholesale colocation site","Retail cage deployment","High-density AI cluster","Disaster recovery site","Interconnection portfolio"]}),
feature("sla-credit-calculation","CRO11","SLA credit calculation","Reconcile sla credit calculation using MSAs, order forms, rack and cross-connect inventories, utility readings, PUE formulas, tickets, telemetry, and invoices.","Produce a governed sla credit calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["provider","Colocation Provider","text","Atlas Data Centers"],["site","Facility / Cage","text","IAD-04 Cage C18"],["invoicedAmount","Invoiced Amount","currency",428000],["contractAmount","Contract-Supported Amount","currency",379500]],{amountField:"invoicedAmount",subjects:["Wholesale colocation site","Retail cage deployment","High-density AI cluster","Disaster recovery site","Interconnection portfolio"]}),
feature("capacity-commitment-tracking","CRO12","Capacity commitment tracking","Reconcile capacity commitment tracking using MSAs, order forms, rack and cross-connect inventories, utility readings, PUE formulas, tickets, telemetry, and invoices.","Produce a governed capacity commitment tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["provider","Colocation Provider","text","Atlas Data Centers"],["site","Facility / Cage","text","IAD-04 Cage C18"],["invoicedAmount","Invoiced Amount","currency",428000],["contractAmount","Contract-Supported Amount","currency",379500]],{amountField:"invoicedAmount",subjects:["Wholesale colocation site","Retail cage deployment","High-density AI cluster","Disaster recovery site","Interconnection portfolio"]}),
feature("invoice-exception-workbench","CRO13","Invoice exception workbench","Reconcile invoice exception workbench using MSAs, order forms, rack and cross-connect inventories, utility readings, PUE formulas, tickets, telemetry, and invoices.","Produce a governed invoice exception workbench decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["provider","Colocation Provider","text","Atlas Data Centers"],["site","Facility / Cage","text","IAD-04 Cage C18"],["invoicedAmount","Invoiced Amount","currency",428000],["contractAmount","Contract-Supported Amount","currency",379500]],{amountField:"invoicedAmount",subjects:["Wholesale colocation site","Retail cage deployment","High-density AI cluster","Disaster recovery site","Interconnection portfolio"]}),
feature("provider-claim-and-response-tracking","CRO14","Provider claim and response tracking","Reconcile provider claim and response tracking using MSAs, order forms, rack and cross-connect inventories, utility readings, PUE formulas, tickets, telemetry, and invoices.","Produce a governed provider claim and response tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["provider","Colocation Provider","text","Atlas Data Centers"],["site","Facility / Cage","text","IAD-04 Cage C18"],["invoicedAmount","Invoiced Amount","currency",428000],["contractAmount","Contract-Supported Amount","currency",379500]],{amountField:"invoicedAmount",subjects:["Wholesale colocation site","Retail cage deployment","High-density AI cluster","Disaster recovery site","Interconnection portfolio"]}),
feature("recovery-and-unit-cost-analytics","CRO15","Recovery and unit-cost analytics","Reconcile recovery and unit-cost analytics using MSAs, order forms, rack and cross-connect inventories, utility readings, PUE formulas, tickets, telemetry, and invoices.","Produce a governed recovery and unit-cost analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["provider","Colocation Provider","text","Atlas Data Centers"],["site","Facility / Cage","text","IAD-04 Cage C18"],["invoicedAmount","Invoiced Amount","currency",428000],["contractAmount","Contract-Supported Amount","currency",379500]],{amountField:"invoicedAmount",subjects:["Wholesale colocation site","Retail cage deployment","High-density AI cluster","Disaster recovery site","Interconnection portfolio"]})
]);
